Update install_SsaCli

diff --git a/install_SsaCli b/install_SsaCli
--- a/install_SsaCli
+++ b/install_SsaCli
@@ -22,38 +22,32 @@ sed -i "s/^ServerActive=.*/ServerActive=$STATIC_IP/" /etc/zabbix/zabbix_agent2.c
 sed -i "s/^Hostname=.*/Hostname=$SERVER_IP/" /etc/zabbix/zabbix_agent2.conf
 
 cat <<EOF >> /etc/zabbix/zabbix_agent2.conf
-UserParameter=raid.status.custom,/usr/local/bin/check_raid_status_custom.sh
-UserParameter=raid.status,cat /proc/mdstat | grep -E '\[.*_.*\]' | wc -l
-UserParameter=network.discovery,/usr/local/bin/discover_network_interfaces.sh
+UserParameter=raid.disk_status,/usr/local/bin/check_ssacli_status.sh
 EOF
 
 # Tạo script kiểm tra RAID
 echo "👉 Tạo script kiểm tra RAID..."
-cat <<'EOF' > /usr/local/bin/check_raid_status_custom.sh
+cat <<'EOF' > /usr/local/bin/check_ssacli_status.sh
 #!/bin/bash
-raid_arrays=$(cat /proc/mdstat | grep ^md | awk '{print $1}')
-total_failed_devices=0
-for array in $raid_arrays; do
-    failed_devices=$(sudo mdadm --detail /dev/$array | grep "Failed Devices" | awk '{print $4}')
-    total_failed_devices=$((total_failed_devices + failed_devices))
-done
-echo $total_failed_devices
-EOF
-
-# Tạo script phát hiện interface mạng
-echo "👉 Tạo script phát hiện interface mạng..."
-cat <<'EOF' > /usr/local/bin/discover_network_interfaces.sh
-#!/bin/bash
-ip -br link | awk '$2 == "UP" {print $1}' | jq -R -s -c 'split("\n")[:-1] | map({"{#IFNAME}": .})'
+slot=$(sudo /usr/sbin/ssacli controller all show | grep -oP '(?<=Slot )[0-9]+')
+if [ -z "$slot" ]; then
+    echo "No RAID controller detected! Please check if the RAID controller is properly recognized."
+    exit 1
+fi
+output=$(sudo /usr/sbin/ssacli controller slot=$slot physicaldrive all show status | grep -E 'physicaldrive' | grep -v 'OK')
+if [ -z "$output" ]; then
+    echo "OK"
+else
+    echo "FAIL"
+fi
 EOF
 
 # Cấp quyền thực thi cho các script
-chmod +x /usr/local/bin/check_raid_status_custom.sh
-chmod +x /usr/local/bin/discover_network_interfaces.sh
+chmod +x /usr/local/bin/check_ssacli_status.sh
 
 # Thêm quyền sudo cho Zabbix để chạy mdadm mà không cần mật khẩu
 echo "👉 Cấu hình sudo cho Zabbix..."
-echo "zabbix ALL=(ALL) NOPASSWD: /usr/sbin/mdadm" | sudo tee -a /etc/sudoers > /dev/null
+echo "zabbix ALL=(ALL) NOPASSWD: /usr/sbin/ssacli" | sudo tee -a /etc/sudoers > /dev/null
 
 # Mở cổng firewall cho Zabbix Agent
 echo "👉 Cấu hình firewall..."
